name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  spelling:
    name: Typos
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: crate-ci/typos@master
